// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjqbpkblutbdpfzzwxmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcWJwa2JsdXRiZHBmenp3eG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxOTc1MDAsImV4cCI6MjA4NDc3MzUwMH0.rpDIWEclzUSg4zFnNv-ApOUGm1dGKyGldtx4LB5CHVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});